### ISSUE TITLE
 Request to Contribute to Your Project

### ISSUE THREAD

**Issue by singlefleck** [jarlah/JourniPlan#1]
Hi Jariah,

I'm Srujan, an Elixir developer working at GRN Connect. I had a similar idea focused on splitting expenses during trips. While browsing GitHub, I came across your project and found it even more interesting than mine. I'd love to contribute to it in my free time, as I believe it would help me strengthen my skills in LiveView.

Since it's your project, please let me know what needs to be done. If possible, create tasks and assign them to me.

Looking forward to your response!

Best regards,
Srujan

**Comment by jarlah** [comment]
What a positive suprise ✌️ but of course. I am mainly just playing around with it now.

I wanted to go a bit off road by using commanded library. Its just a slight cqrs/es abstraction. Makes it possible to make projections for an event log maybe in future.

Ill just get the seeds working, then i will look into how we can collaborate.

**Comment by jarlah** [comment]
ok, done ;) poor mans excuse for tests that also works as a quick way to test that things work: seeds ;)

**Comment by jarlah** [comment]
added you :) wont do any harm anyway :) And its good to have someone with a shared interest.

Right now all the tests doesnt pass because i dont log in a user in the live tests. 

Maybe you can look into that ? Or, it might not be important if we are redesigning the live view(s). 

Just add some issues to work on so i can see what you are doing. Ill do the same

**Comment by singlefleck** [comment]
Thanks for adding me, @jarlah! I’ll take a look at the live tests and see what’s going on with the user login.

Excited to dive in and collaborate further! Let me know if there’s anything specific you’d like me to prioritize.

**Comment by jarlah** [comment]
I was a bit silly and fixed them! But do not worry :) its not even started yet ;) .. i suggest looking into the project and getting familiar with it. I have a PR open, you could look at that too
